### ISSUE TITLE
error: cannot find attribute `argh` in this scope

### ISSUE THREAD

**Issue by sviscapi** [thetawavegame/thetawave#174]
Dear @varoonp123 ,

I got the following error when trying to compile Thetawave from a fresh "git clone" on Debian 11 "Bullseye" x86_64:

    cargo build --release --features storage --features arcade
    [...]
    Compiling thetawave v0.1.1 (/home/samuel/src/thetawave)
    error: cannot find attribute `argh` in this scope
      --> src/options/mod.rs:49:9
       |
    49 |         argh(switch, short = 'a')
       |         ^^^^

    error: could not compile `thetawave` (bin "thetawave") due to 1 previous error

What am I doing wrong ? 

    cargo 1.79.0-nightly (80d5b607d 2024-04-19)
    rustc 1.79.0-nightly (dbce3b43b 2024-04-20)

Best regards,

Samuel

**Comment by varoonp123** [comment]
I goofed a bit in the conditional compilation and will push up a fix later today. Thanks for reminding me of this :) 

You can also do `cargo build --features cli` but by the end of the day, that feature will truly be optional and default to basically the same behavior as in the browser.
