### ISSUE TITLE
Set up GitHub Actions to build for different platforms/architectures

### ISSUE THREAD

**Issue by orhun** [thetawavegame/thetawave#27]
Hello!

Since `thetawave` is a part of [SpicyLauncher](https://github.com/spicylobstergames/SpicyLauncher) now, we need more release assets for supporting more platforms.

It would be nice to have a GitHub Actions workflow that runs when a release is created for distributing binary archives. For example:

- https://github.com/fishfolk/jumpy/blob/main/.github/workflows/release.yml
- https://github.com/fishfolk/punchy/blob/master/.github/workflows/cd.yml

**Comment by cdsupina** [comment]
#33
