### ISSUE TITLE
Increase size of health bar UI

### ISSUE THREAD

**Issue by cdsupina** [thetawavegame/thetawave#47]
The health and shield bars are too small. We should make their UI larger and easier for players to keep track of.

**Comment by cdsupina** [comment]
A larger health bar may not be strictly necessary, but more feedback when the enemy is damaged would definitely be helpful.

**Comment by dh337071** [comment]
I was thinking about this and in other shmups enemies tend to "flash white" when they are hit.

edit: I just realized you made a similar comment back in May,

**Comment by cdsupina** [comment]
Ui updated
